Assertion alpha implementation
The login form, server handler and JS library are
implemented but when the authenticator is called
throws:
DOMException: An attempt was made to use an object that is not, or is no longer, usable